version: '3'
services:
  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  web:
    image: php:7.2-apache
    depends_on:
      - database
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80